version: 2
jobs:
  build:
    docker:
      - image: "python:latest"
    steps:
      - checkout
      - run:
          name: Getting Environment Ready
          command: |
            pip install --upgrade pip 1> /dev/null
            curl -LsSf https://astral.sh/uv/install.sh | sh
            uv sync --frozen --no-install-project --no-dev --python-preference=only-system
      - run:
          name: Python Version Info
          command: uv run python --version
      - run:
          name: Check Python Programs
          command: uv run bash check.sh
      - run:
          name: Run Tests
          command: uv run py.test --verbose
